### ISSUE TITLE
example telegraf scraping config

### ISSUE THREAD

**Issue by jordens** [quartiq/miniconf#139]
Posting it here as it affects all stabilizer/stabilizer-fls/booster/thermostat-mqtt/thermostat-eem.

This should be integrated into the docs to give people a head start. Also the common docs that are more miniconf-specific from both [booster](https://quartiq.de/booster/network-interface.html) and [stabilizer](https://quartiq.de/stabilizer/usage.html) should both be replaced with and reference to miniconf docs.

Should cover topic_parsing, logging settings and telemetry, scaling considerations.

`/etc/telegraf/telegraf.d/miniconf-telemetry.conf`

```toml
[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt:1883"]
  topics = [
    "dt/sinara/dual-iir/+/telemetry",
    "dt/sinara/lockin/+/telemetry",
  ]
  data_format = "json"
```
